services:
  mysql:
    image: mysql:8.4
    container_name: mysql-sgbd
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: contraseña_root
      MYSQL_DATABASE: nombre_base_datos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña_usuario
    volumes:
      - mysql_sgbd:/var/lib/mysql

volumes:
  mysql_sgbd:
