INSERT INTO producto(nombre, familia_id, descripcion, precio)
VALUES
('Pescado Frito + Café + Yuca', 1, '(Pescado, café, yuca hervida, zarza)', 15),
('Chilcano Económico', 1, '(Pescado, Fumet, arroz, choros)', 6),
('Costilla Frita de Cerdo', 1, '(Costilla dorada, yuca, zarza criolla)', 30),
('Chicharrón + Café', 1, '(Porción de chicharrón de cerdo, café, zarza)', 20),
('RONDA PIURANA', 2, 'Seco de chabelo, majado de yuca, cecina, chicharrón de chancho, ceviche de caballa, jarra de  chicha de jora.', 80),
('ESPECIAL  "PIURANO"', 2, 'Ceviche de cachema, ceviche de caballa, seco de chabelo, chicharrón de pescado.', 60),
('SECO DE CHABELO', 2, 'Crujiente cecina, plátano verde, crujiente cancha, zarza.', 35),
('MAJADO DE YUCA', 2, 'Yuca chancada, cecina de chancho, chifle , cancha, zarza.', 32),
('MAJARISCO', 2, 'Plátano verde, langostino, calamar, almejas.', 38),
('CARNE SECA', 2, 'Cecina, chifles, platacones, zarza.', 35),
('CARNE ALIÑIADA', 2, 'Carne oreada, chifles, platacones, zarza.', 35),
('PASADITO POR AGUA CALIENTE', 2, 'Pescado caballa, yuca y zarza.', 30),
('CANGREJO REVENTADO', 2, 'Cangrejo, papa sancochada.', 40),
('GUISADA DE TOLLO', 2, 'Pez tollo en base de escabeche mas guarnición.', 18),
('TOLLITO GUISADO', 2, 'Pez tollo sancochado, deshuesado con arroz.', 30),
('PATASQUITA PIURANA', 2, 'Mote, mondonguito, pellejito de chancho, fumet.', 20),
('CAUSA NORTEÑA', 2, 'Puré de papa, pescado encebollado, choiclo, camote, plátano sancochado, yuca.', 40),
('CAZUELA DE LANGOSTINOS Y PULPO', 2, 'Langostino, pulpo, fumet.', 40),
('CEVICHE MIXTO "PIURANO"', 2, 'Zumo de limón, ceviche cabrilla, ceviche conchas negras, ceviche caballa.', 60),
('SOPA DE NOVIOS', 2, 'Fumet, fideo, aceituna, pasas, (cabrito o pato)', 30),
('Ceviche Simple', 3, '(Pescado, zumo de limón, sal, cebolla, guarniciones)', 30),
('Ceviche Mixto', 3, '(Pescado, zumo de limón, sal, cebolla, mariscos, guarniciones)', 32),
('Ceviche Mariscos', 3, '(Mariscos, zumo de limón, sal, cebolla, guarniciones)', 32),
('Ceviche Pulpo', 3, '(Pulpo, zumo de limón, sal, cebolla, guarniciones)', 33),
('Ceviche Langostinos', 3, '(Langostinos, zumo de limón, sal, cebolla, guarniciones)', 34),
('Ceviche Corvina', 3, '(Pez corvina, zumo de limón, sal, cebolla, guarniciones)', 40),
('Ceviche Cachema', 3, '(Pez cachema, zumo de limón, sal, cebolla, guarniciones)', 30),
('Ceviche Ojo de Uva', 3, '(Pez Ojo de Uva, zumo de limón, sal, cebolla, guarniciones)', 40),
('Ceviche de Cangrejos', 3, '(Cangrejos, zumo de limón, sal, cebolla, guarniciones)', 30),
('Ceviche de Caballa', 3, '(Caballa salpresa, zumo de limón, sal, cebolla, tomate, guarniciones)', 25),
('Choros a la Chalaca', 3, '(Choros, zumo de limón, sal, cebolla, tomate, guarnición)', 25),
('Tiradito Clásico', 3, '(Láminas de pescado, salsa de ajíes peruanos)', 30),
('Leche de Tigre', 3, '(Pescado, leche de tigre de ají limo, cebolla)', 15),
('Chaufa de Mariscos', 4, 'Arroz, mariscos, huevo', 28),
('Chaufa de Pescado', 4, 'Arroz, pescado, huevo', 30),
('Chaufa de Langostinos', 4, 'Arroz, langostinos, huevo', 30),
('Chaufa de Pulpo', 4, 'Arroz, pulpo, huevo', 33),
('Chaufa Especial', 4, 'Arroz, tocino, mariscos', 30),
('Chaufa de Pollo', 4, 'Arroz, pollo, huevo', 28),
('Chicharrón Simple', 5, 'Pescado empanizado, yuca frita y zarza.', 30),
('Chicharrón Mixto', 5, 'Pescado empanizado, mariscos empanizados, yuca frita y zarza.', 32),
('Chicharrón de Mariscos', 5, 'Mariscos empanizados, yuca frita y zarza.', 32),
('Chicharrón de Pulpo', 5, 'Pulpo empanizado, yuca frita y zarza.', 35),
('Chicharrón de Langostinos', 5, 'Langostinos empanizados, yuca frita y zarza.', 35),
('Chicharrón de Calamar', 5, 'Calamar empanizado, yuca frita y zarza.', 32),
('Cachema Encebollada', 5, 'Cachema, cebolla, tomate, camote y chifles.', 30),
('Jalea Mixta', 5, 'Filete de pescado apanado, chicharrón de pescado con mariscos, yuca frita y zarza.', 38),
('Chita Frita', 5, 'Pez Chita frita, zarza criolla, yuca y/o arroz.', 40),
('Mero Frito', 5, 'Pez Mero frito, zarza criolla, yuca y/o arroz.', 40),
('Cachema Frita', 5, 'Pez Cachema frita, zarza criolla, yuca y/o arroz.', 30),
('Corvina Frita', 5, 'Pez Corvina frita, zarza criolla, yuca y/o arroz.', 40),
('Corvina Frita "Filete"', 5, 'Pez Corvina frita filete, zarza criolla, yuca y/o arroz.', 40),
('Apanado de Corvina Frita', 5, 'Pez Corvina apanado, zarza, arroz, yuca frita.', 40),
('Tollo Apanado', 5, 'Pez Tollo apanado, zarza, arroz, yuca frita.', 25),
('Escabeche de Pescado', 5, 'Pescado frito, cebolla agria, yuca frita.', 25),
('Pescado a lo Macho', 5, 'Pescado frito, picante de mariscos, camote.', 50),
('Pescado al Ajo', 5, 'Pescado frito, crema de ajo.', 35),
('Pescado en Salsa de Langostinos', 5, 'Pescado frito, crema de langostinos', 50),
('Dúos Marinos', 6, '2 porciones a escoger: Arroz con mariscos, Chicharrón o Ceviche.', 25),
('Tríos Marinos', 6, 'Ceviche, Arroz con mariscos y Chicharrón.', 30),
('Menú Marino 1', 7, 'Chilcano, arroz con mariscos, vaso clarito.', 15),
('Menú Marino 2', 7, 'Chilcano, arroz, pescado frito, vaso clarito.', 15),
('Lomo Saltado', 8, 'Lomo, papa frita, arroz.', 30),
('Pollo a la Plancha', 8, 'Pollo, papa frita, arroz.', 25),
('Pato Guisado', 8, 'Pato, yuca, arroz menestra o yuca.', 30),
('Cabrito', 8, 'Cabrito, yuca, arroz menestra o yuca.', 30),
('Chifles', 9, 'Láminas de plátano', 10),
('Patacones', 9, 'Rodaja chancada de plátano frito', 10),
('Arroz blanco', 9, '', 5),
('Yuca o camote', 9, '', 5),
('Cancha', 9, '', 5),
('Ceviches', 10, '', 90),
('Chicharrones', 10, '', 90),
('Arroz Con Mariscos', 10, '', 90),
('Sudados', 10, '', 90),
('Chupe de Pescado', 11, 'Pescado, arroz, papa, huevo', 25),
('Chupe de Cangrejos', 11, 'Cangrejo, arroz, papa, huevo', 30),
('Chupe de Langostinos', 11, 'Langostinos, arroz, papa, huevo', 30),
('Chupe de Camarones', 11, 'Camarones, arroz, papa, huevo', 30),
('Chupe de Mero', 11, 'Pez Mero, arroz, papa, huevo', 45),
('Chupe de Mariscos', 11, 'Mariscos, arroz, papa, huevo', 32),
('Chupe de Ojo de Uva', 11, 'Pez Ojo de Uva, arroz, papa, huevo', 40),
('Chupe de Corvina', 11, 'Pez Corvina, arroz, papa, huevo', 40);



