INSERT INTO familia(nombre)
VALUES
('desayunos'),
('especialidades'),
('ceviches'),
('chaufas'),
('frituras'),
('duos y trios'),
('menu piurano'),
('criollos'),
('guarniciones'),
('fuentes'),
('chupes'),
('tortillas'),
('arroces'),
('chilcanos'),
('parihuelas'),
('sudados'),
('cena'),
('piqueos'),
('bebidas'),
('tragos'),
('vinos'),
('infusiones');
