INSERT INTO mesa (estado) VALUES
('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'),
('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'),
('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'),
('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'),
('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'),
('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'),
('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'),
('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'),
('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'),
('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE'), ('LIBRE');
